"""empty message

Revision ID: dffbb2f1f736
Revises: 
Create Date: 2020-08-02 20:14:25.485332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffbb2f1f736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classcode_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=False),
    sa.Column('classname', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id')
    )
    op.create_table('student_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('day', sa.String(length=255), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classcode_table.class_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_table')
    op.drop_table('student_table')
    op.drop_table('classcode_table')
    # ### end Alembic commands ###
